spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/java-beans-cafe
    username: portal_local_user
    password: portal_local_pass
    driver-class-name: org.postgresql.Driver

  mail:
    properties:
      mail:
        smtp:
          starttls:
            enable: true
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true


topicos:
  pagamento:
    request:
      topic: "pagamento.request.topic.v1"